name: Tests

on:
  push:
    branches: [ "**" ]
    tags: [ "!api"]
  pull_request:
    branches: [ "main" ]
    tags: [ "!api"]
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 18
        -  run: npm ci
        -  run: npx playwright install
        -  run: npx playwright test
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
